version: "3.3"
services:
  postgresdb:
    container_name: postgres
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
      - ./prisma/configuredb:/configureScripts
    env_file:
      - prisma/.env
  app:
    image: "money-service-image"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - prisma/.env
    depends_on:
      - postgresdb

volumes:
  configuredb: