version: "3.3"
services:
  postgresdb:
    container_name: postgres
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    env_file:
      - prisma/.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "ckan" ]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  app:
    image: "money-service-image"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - prisma/.env
    depends_on:
      - postgresdb